/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import express, { Request, Response } from "express";
import path from "path";
import dotenv from "dotenv";
import { createServer as createViteServer } from "vite";
import { mlPipeline } from "./src/lib/ml";
import { defaultDataset } from "./src/lib/dataset";
import { SentimentHistoryDB } from "./src/lib/db";
import { GoogleGenAI, Type } from "@google/genai";

// Load environment variables
dotenv.config();

const app = express();
const PORT = 3000;

// Enable JSON bodies
app.use(express.json({ limit: "50mb" }));

// Pre-train our custom machine learning pipeline on boot
console.log("Initializing Sentiment Analysis Machine Learning Model...");
try {
  const historyLogs = mlPipeline.train(defaultDataset);
  console.log(`Model successfully trained on default dataset with ${defaultDataset.length} reviews! Vocabulary size: ${mlPipeline.vectorizer.vocabulary.length} words.`);
} catch (e) {
  console.error("Failed to train Machine Learning Model on startup:", e);
}

// Lazy initialization of Gemini client
let ai: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI | null {
  if (ai) return ai;
  const apiKey = process.env.GEMINI_API_KEY;
  if (apiKey && apiKey !== "MY_GEMINI_API_KEY") {
    ai = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        }
      }
    });
    return ai;
  }
  return null;
}

// API Routes
app.get("/api/health", (req: Request, res: Response) => {
  res.json({ status: "healthy", timestamp: new Date().toISOString() });
});

// 1. Analyze single text
app.post("/api/analyze", async (req: Request, res: Response) => {
  try {
    const { text, generateSuggestions = false, source = "Single Text", tag = "General" } = req.body;

    if (!text || typeof text !== "string") {
       res.status(400).json({ error: "Text field is required and must be a string." });
       return;
    }

    // Run ML pipeline
    const analysis = mlPipeline.analyze(text);

    // Save to historical database record
    const saved = SentimentHistoryDB.add({
      text,
      sentiment: analysis.sentiment,
      score: analysis.score,
      confidence: analysis.confidence,
      source,
      tag
    });

    // Generate AI suggestions through Gemini if requested and API Key is available
    let aiSuggestions: string | null = null;
    const client = getGeminiClient();
    
    if (generateSuggestions && client) {
      try {
        const prompt = `You are an expert NLP Sentiment Analysis Assistant. 
Analyze the customer's text: "${text}".
The custom mathematical model classified this as ${analysis.sentiment.toUpperCase()} sentiment with a confidence of ${(analysis.confidence * 100).toFixed(1)}% and score of ${analysis.score.toFixed(2)} (-1 representing totally negative, +1 representing totally positive).

Provide exactly 3 highly actionable, bulleted suggestions or takeaways concerning how a business or writer should react to this feedback. Keep the suggestions short, specific, and professional. Do NOT include markdown introduction or conclusion lines; start directly with the bullet points.`;

        const response = await client.models.generateContent({
          model: "gemini-3.5-flash",
          contents: prompt,
        });

        aiSuggestions = response.text || "No suggestions generated by AI.";
      } catch (gemIniError: any) {
        console.error("Gemini API Error:", gemIniError);
        aiSuggestions = `Failed to generate suggestions via Gemini: ${gemIniError.message || gemIniError}`;
      }
    } else if (generateSuggestions) {
      aiSuggestions = "Gemini API key is not configured in Secrets settings. Suggestions are disabled.";
    }

    res.json({
      id: saved.id,
      timestamp: saved.timestamp,
      analysis,
      aiSuggestions
    });
  } catch (err: any) {
    console.error("Single analysis endpoint error:", err);
    res.status(500).json({ error: err.message || "An error occurred during analysis." });
  }
});

// 2. Query model stats & classification metrics
app.get("/api/model/stats", (req: Request, res: Response) => {
  try {
    const stats = mlPipeline.getStats();
    res.json(stats);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// 3. Train custom model dynamically!
app.post("/api/model/train", (req: Request, res: Response) => {
  try {
    const { dataset, testRatio = 0.2 } = req.body;
    let epochsLogs;

    if (dataset && Array.isArray(dataset) && dataset.length >= 10) {
      // Validate structure
      const validDataset = dataset.every(item => 
        item && 
        typeof item.text === "string" && 
        ["positive", "negative", "neutral"].includes(item.sentiment)
      );
      if (!validDataset) {
         res.status(400).json({ error: "Invalid dataset format. Must be an array of objects with 'text' and 'sentiment' (positive/negative/neutral)." });
         return;
      }
      epochsLogs = mlPipeline.train(dataset, testRatio);
    } else {
      // Reset to default dataset
      epochsLogs = mlPipeline.train(defaultDataset, testRatio);
    }

    const updatedStats = mlPipeline.getStats();
    res.json({
      success: true,
      message: "Model trained successfully!",
      stats: updatedStats
    });
  } catch (err: any) {
    console.error("Training endpoint error:", err);
    res.status(500).json({ error: err.message });
  }
});

// 4. Bulk upload reviews (CSV Upload processed into JSON array)
app.post("/api/bulk-analyze", (req: Request, res: Response) => {
  try {
    const { items } = req.body; // Array of { text, source, tag }

    if (!items || !Array.isArray(items) || items.length === 0) {
       res.status(400).json({ error: "An array of items is required." });
       return;
    }

    // Process all and compile database insertion models
    const recordsToSave = items.map(item => {
      const text = item.text || "";
      const analysis = mlPipeline.analyze(text);
      return {
        text,
        sentiment: analysis.sentiment,
        score: analysis.score,
        confidence: analysis.confidence,
        source: item.source || "CSV Upload",
        tag: item.tag || "Bulk Data"
      };
    });

    const savedRecords = SentimentHistoryDB.addMany(recordsToSave);

    res.json({
      success: true,
      count: savedRecords.length,
      records: savedRecords
    });
  } catch (err: any) {
    console.error("Bulk analysis endpoint error:", err);
    res.status(500).json({ error: err.message });
  }
});

// 5. Retrieve analysis history
app.get("/api/history", (req: Request, res: Response) => {
  try {
    const { search, sentiment } = req.query;
    const items = SentimentHistoryDB.getAll(
      search ? String(search) : undefined,
      sentiment ? String(sentiment) : undefined
    );
    res.json(items);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// 6. Retrieve dashboard aggregates & percentage stats
app.get("/api/history/stats", (req: Request, res: Response) => {
  try {
    const stats = SentimentHistoryDB.getDashboardStats();
    res.json(stats);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// 7. Delete individual items
app.delete("/api/history/:id", (req: Request, res: Response) => {
  try {
    const id = req.params.id;
    const deleted = SentimentHistoryDB.delete(id);
    if (deleted) {
      res.json({ success: true, message: `Record ${id} deleted.` });
    } else {
      res.status(404).json({ error: `Record ${id} not found.` });
    }
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// 8. Wipe history database
app.post("/api/history/clear", (req: Request, res: Response) => {
  try {
    SentimentHistoryDB.clear();
    res.json({ success: true, message: "History database cleared successfully." });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// 9. AI executive dashboard insights via Gemini
app.post("/api/gemini/insights", async (req: Request, res: Response) => {
  try {
    const client = getGeminiClient();
    if (!client) {
       res.json({ insights: "Gemini API key is not configured in Secrets. Configure it under Settings > Secrets to unlock dynamic AI strategic metrics." });
       return;
    }

    const items = SentimentHistoryDB.getAll();
    const stats = SentimentHistoryDB.getDashboardStats();

    if (items.length === 0) {
       res.json({ insights: "No data available in the analysis history yet. Analyze some text feedback samples first!" });
       return;
    }

    // Sample down key text items of negative/positive to save tokens
    const recentNegativeDoc = items.filter(i => i.sentiment === "negative").slice(0, 5).map(i => `- "${i.text}"`).join("\n");
    const recentPositiveDoc = items.filter(i => i.sentiment === "positive").slice(0, 5).map(i => `- "${i.text}"`).join("\n");

    const prompt = `You are a Chief Marketing and Operations AI Analyst. 
The system analyzed a total of ${stats.totalAnalyzed} feedback items.
Overall Statistics:
- Positive Sentiment: ${stats.positiveCount} items (${stats.positivePercentage}%)
- Negative Sentiment: ${stats.negativeCount} items (${stats.negativePercentage}%)
- Neutral Sentiment: ${stats.neutralCount} items (${stats.neutralPercentage}%)
- Averaged Composite Score: ${stats.averageScore.toFixed(3)} (-1 to +1 range)

Recent Critical Complaints (Negative Feedback):
${recentNegativeDoc || "none yet"}

Recent Customer Accolades (Positive Feedback):
${recentPositiveDoc || "none yet"}

Provide a highly professional, 2-3 paragraph Executive Briefing of strategic takeaways, pinpointing the primary failure/success themes (e.g. support speed, product bugs, delivery delays, design appeal) and recommending immediate operational solutions. Use clean bullet points underneath! Make it sound extraordinarily smart, suited for an executive presentation.`;

    const response = await client.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
    });

    res.json({ insights: response.text || "No strategic feedback generated." });
  } catch (err: any) {
    console.error("Executive insights endpoint error:", err);
    res.status(500).json({ error: err.message });
  }
});

// 10. AI Actionable strategic suggestions based on history and ML keywords
app.post("/api/gemini/suggestions", async (req: Request, res: Response) => {
  try {
    const client = getGeminiClient();

    // Get statistics & keywords from our local model stats
    const modelStats = mlPipeline.getStats();
    const items = SentimentHistoryDB.getAll();

    // In case no Gemini API key is configured or we want fallback, we return rich default suggestions
    if (!client) {
      // Fallback suggestions
      const fallbackSuggestions = [
        {
          id: "sug_fallback_1",
          title: "Improve Customer Support Response Velocity",
          category: "Customer Service",
          sentimentFocus: "Negative",
          impact: "High",
          explanation: "Multiple negative customer reviews focus on slow response times or being left on read. Our TF-IDF predictive keywords emphasize standard delay markers.",
          actionPlan: [
            "Integrate a real-time support chat widget into the landing page.",
            "Formulate auto-response macros to handle frequently asked setup questions.",
            "Establish a clear internal target of under 2 hours for high-priority complaints."
          ]
        },
        {
          id: "sug_fallback_2",
          title: "Optimize Mobile App Load Speeds & Fix Freezes",
          category: "Performance",
          sentimentFocus: "Negative",
          impact: "Medium",
          explanation: "Negative feedback points to performance lag, loading delays, and app freezing on larger screen displays.",
          actionPlan: [
            "Audit frontend asset bundle sizes and apply route lazy-loading.",
            "Cache historical database queries on the client state instead of re-fetching.",
            "Improve error boundaries to prevent app freezing during socket disruptions."
          ]
        },
        {
          id: "sug_fallback_3",
          title: "Leverage Clean Interface Design in Marketing",
          category: "Product & Marketing",
          sentimentFocus: "Positive",
          impact: "Low",
          explanation: "Strong positive reviews praise the minimal aesthetics, smooth animations, and overall clean design of Sentix.AI. Leverage these attributes in public showreels.",
          actionPlan: [
            "Highlight the modern dark mode and visual graph features in promotional posts.",
            "Invite active users to submit their success case studies on Product Hunt.",
            "Design custom tutorial modals that guide new customers with the same micro-interactions."
          ]
        }
      ];
      res.json({ suggestions: fallbackSuggestions, isDemo: true });
      return;
    }

    if (items.length === 0) {
      res.json({ suggestions: [], isDemo: false, message: "No data available in analysis history yet. Analyze some feedback samples first!" });
      return;
    }

    // Sample down key text items of negative/positive/neutral to save tokens
    const recentNegativeDoc = items.filter(i => i.sentiment === "negative").slice(0, 8).map(i => `- "${i.text}"`).join("\n");
    const recentPositiveDoc = items.filter(i => i.sentiment === "positive").slice(0, 8).map(i => `- "${i.text}"`).join("\n");
    
    // Extrapolate top predictive words
    const topNegWords = modelStats.topWordsPerClass.negative.slice(0, 10).map(w => `${w.word} (weight: ${w.weight.toFixed(2)})`).join(", ");
    const topPosWords = modelStats.topWordsPerClass.positive.slice(0, 10).map(w => `${w.word} (weight: ${w.weight.toFixed(2)})`).join(", ");

    const prompt = `You are an elite Operations and Customer Experience (CX) AI Analyst. 
We have analyzed the sentiment and predictive keywords from user feedback.

Here are the top predictive vocabulary words mapped to Negative and Positive sentiments by our TF-IDF + Logistic Regression Machine Learning model:
- Top Negative Influence Words: ${topNegWords || "none computed yet"}
- Top Positive Influence Words: ${topPosWords || "none computed yet"}

Here is a sample of actual recent critical user complaints (Negative Sentiment):
${recentNegativeDoc || "none recorded yet"}

Here is a sample of actual recent user accolades (Positive Sentiment):
${recentPositiveDoc || "none recorded yet"}

Your task is to analyze these sentiments, complaints, praises, and predictive keyword weights. 
Generate exactly 3 to 4 highly strategic, actionable operational suggestions.
For example, if negative reviews or words highlight support speed or response time, suggest concrete steps like "Optimize customer support response speed". 
If positive reviews or words praise the intuitive layout, suggest "Leverage intuitive UX elements to boost engagement".

You must output a JSON list of suggestions strictly adhering to the specified schema rules. Do not include markdown wraps or anything except a valid JSON array.`;

    const response = await client.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              id: { type: Type.STRING },
              title: { type: Type.STRING, description: "Actionable strategic suggestion title. Keep it short and impactful." },
              category: { type: Type.STRING, description: "Operational category, e.g. 'Customer Support', 'Product Feature', 'Performance', 'Marketing'" },
              sentimentFocus: { type: Type.STRING, description: "Must be exactly one of: 'Positive', 'Negative', 'Neutral', 'Both'" },
              impact: { type: Type.STRING, description: "Must be exactly one of: 'High', 'Medium', 'Low'" },
              explanation: { type: Type.STRING, description: "Explain the rationale linking this suggestion to the specific complaints, accolades, or keywords analyzed." },
              actionPlan: {
                type: Type.ARRAY,
                items: { type: Type.STRING },
                description: "Array of 3 concrete, sequential steps to implement the suggestion."
              }
            },
            required: ["id", "title", "category", "sentimentFocus", "impact", "explanation", "actionPlan"]
          }
        }
      }
    });

    const textOutput = response.text || "[]";
    const suggestions = JSON.parse(textOutput);
    res.json({ suggestions, isDemo: false });
  } catch (err: any) {
    console.error("Suggestions generator endpoint error:", err);
    res.status(500).json({ error: err.message || "An error occurred generating suggestions." });
  }
});

// Vite Middleware for development
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    // Serve production static build assets
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req: Request, res: Response) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
